export enum PropertyMessage {
  PROPERTY_NOT_EXISTS = 'Property does not exists',
  MEMBERSHIP_NOT_EXISTS = ' Membership plan does not exists',
  PROPERTY_DELETED = 'Property deleted',
  UNAUTHORIZED_ACCESS = 'Unauthorized access',
  INVALID_SERVICE_LOCATION = 'Franchise service location does not exists',
  FRANCHISE_ID_NOT_FOUND = 'Franchise id not found',
  FRANCHISE_NOT_FOUND = 'Franchise not found',
  SERVICE_TYPE_NOT_FOUND = 'Service type not found',
  PREFERRED_VENDOR_ALREADY_EXISTS = 'Preferred vendor already exists',
  SERVICE_TYPE_CATEGORY_NOT_FOUND = 'Franchise service type category not found',
  SERVICE_TYPE_CATEGORY_NOT_ACTIVE = 'Franchise service type category is not active',
  SERVICE_TYPE_CATEGORY_DELETED = 'Franchise service type category is deleted',
  SERVICE_NOT_FOUND = 'Service not found',
}
