export enum AuthMessages {
  SUPER_ADMIN_EXISTS = 'Super Admin Already Exists',
  USER_EXISTS = 'User with this email already exists, please select another email',
  FRANCHISE_ADMIN_EXISTS = 'Franchise Admin Already Exists',
  INVALID_EMAIL = 'User with this email does not exist',
  INVALID_PASSWORD = 'Invalid password',
  FRANCHISE_ADMIN_NOT_FOUND = 'Franchise Admin not found',
  STANDARD_ADMIN_EXISTS = 'Standard Admin Already Exists',
  STANDARD_ADMIN_NOT_FOUND = 'Standard Admin not found',
  FRANCHISE_NOT_FOUND = 'Franchise not found',
  USER_NOT_FOUND = 'User not found',
  ROLE_ACCESS_ERROR = 'Invalid attempt to access role',
  ACCOUNT_DEACTIVATED = 'Your account has been deactivated, kindly contact administrator',
  VENDOR_ACCOUNT_DEACTIVATED = 'Vendor account has been deactivated',
  REQUEST_NOT_FOUND = 'Reset request not found',
  INVALID_ATTEMPT = 'Invalid attempt',
  ACCOUNT_ARCHIVED = 'Your account has been archived, please contact your franchise admin to unarchive your account',
  OWNER_ACCOUNT_ARCHIVED = 'Owner account has been archived',
  EMAIL_ERROR = 'You can request another email after 60 seconds.',
}
